### ISSUE TITLE
`Error: Can't recycle general.salmon_version (size 2) to match general.length_classes (size 5)`

### ISSUE THREAD

**Issue by ks2022ml** [multimeric/TidyMultiqc#7] opened 2022-02-10 04:29 UTC
Hi

I was trying to read the multiQC json file but ran into the following error:
> df = TidyMultiqc::load_multiqc(multiQC_json)
Error: Can't recycle `general.salmon_version` (size 2) to match `general.length_classes` (size 5).

please advise how i can resolve this error. thank you!

**Comment by multimeric** [comment] 2022-02-10 04:33
I guess this must mean that one of the `general` keys in your MultiQC report is present only for some samples and not others, which I didn't know was a possibility. If you can show me a copy of the report, I can probably work out a fix for this.

**Comment by ks2022ml** [comment] 2022-02-10 04:46
it was a large run so the json file is pretty big, is there a particular txt file that would help?

**Comment by multimeric** [comment] 2022-02-10 04:51
I guess if you could copy just the `report_general_stats_data` key from inside the JSON file?

**Comment by ks2022ml** [comment] 2022-02-10 04:58
`    "report_general_stats_data": [
        {
            "L504_293": {
                "salmon_version": "1.5.2",
                "samp_type": "none",
                "opt_type": "vb",
                "quant_errors": [],
                "num_libraries": 1,
                "library_types": [
                    "ISR"
                ],
                "frag_dist_length": 1001,
                "frag_length_mean": 284.40737747398833,
                "frag_length_sd": 70.72713135170152,
                "seq_bias_correct": false,
                "gc_bias_correct": false,
                "num_bias_bins": 4096,
                "mapping_type": "mapping",
                "keep_duplicates": false,
                "num_valid_targets": 194887,
                "num_decoy_targets": 25,
                "num_eq_classes": 248785,
                "serialized_eq_classes": false,
                "eq_class_properties": [
                    "range_factorized",
                    "gzipped"
                ],
                "length_classes": [
                    506,
                    647,
                    1002,
                    2225,
                    104301
                ],
                "index_seq_hash": "9b58cd9a8a74578756dd528b51f5e05eafe206e59de43911766a9772cab69d18",
                "index_name_hash": "70195a8fa07ffd2a653eb2fc058788b811fdd5a3c3f8e9580405d5d5b4076974",
                "index_seq_hash512": "21f96d1689ddd3beea0c8e07e7aeef0352a9cdb86a4b1ad82f5ea88d0eda6797f7e07e085c365b2e61c07f19a6f6dabfaf48029d2930de58220080452508dd0a",
                "index_name_hash512": "64a103794ca96578de0f485832fef4809d870103b17c00e79b85d5b652e0fdf0343e8e0cd5b0dcd06975e5c4dc6dee553cd716647334f80a109d1289a6d117b7",
                "index_decoy_seq_hash": "b6f10dc21c600dd4d204695abe1d70720f3e5e289adc6ad0c7b4bd9adda5d462",
                "index_decoy_name_hash": "eb2a40d949f8e81c1045e1abd04854f1f6cf74edf8e8db9c0754c9ce6c5ded01",
                "num_bootstraps": 0,
                "num_processed": 25468599,
                "num_mapped": 17624899,
                "num_decoy_fragments": 2959299,
                "num_dovetail_fragments": 143003,
                "num_fragments_filtered_vm": 3768142,
                "num_alignments_below_threshold_for_mapped_fragments_vm": 18065896,
                "percent_mapped": 69.20246771328097,
                "call": "quant",
                "start_time": "Tue Feb 01 20:10:56 2022",
                "end_time": "Tue Feb 01 20:29:30 2022"
            },`

**Comment by multimeric** [comment] 2022-02-10 05:04
That's only one sample. Can you give me all of them? For example you could run: `< multiqc_data.json python -c 'import json, sys; print(json.dumps(json.load(sys.stdin)["report_general_stats_data"]))' > general_stats.json`

**Comment by ks2022ml** [comment] 2022-02-10 05:15
sure, here it is:
[general_stats.json.txt](https://github.com/multimeric/TidyMultiqc/files/8038271/general_stats.json.txt)

**Comment by multimeric** [comment] 2022-02-10 05:19
Thanks! Ah I see, it's actually because it's a general statistic that is itself a list. I didn't know MultiQC allowed that. I'll work on a fix.

**Comment by multimeric** [comment] 2022-02-10 05:50
Hi, can you please try installing the proposed fix I have created to see if it solves your issue? Run `remotes::install_github("multimeric/TidyMultiqc@fix-list-general", force=TRUE)`.

**Comment by multimeric** [comment] 2022-02-10 05:52
And could you also please confirm that you are happy for [this (very small) snippet](https://github.com/multimeric/TidyMultiqc/pull/8/files#diff-75ace6daaf227e11377de6db746d7b314c2995c79b0078895f21c88e977a6a34) from your `multiqc_data.json` to be used as a test case. If not I can make up something.

**Comment by ks2022ml** [comment] 2022-02-10 14:03
Yes it works now! Thank you and yes it is ok to use that snippet.

**Comment by wish1832** [comment] 2022-09-20 23:42
Hello,

I recently installed TidyMultiqc (v1.0.2) from CRAN and had the same error message with the same data format (Salmon results from a run with multiple samples). The issue was fixed when I installed the GitHub version (also v1.0.2., with either `devtools::install_github("multimeric/TidyMultiqc")` or `remotes::install_github("multimeric/TidyMultiqc@fix-list-general", force=TRUE)`). Is the version on CRAN updated to include the fix above?

**Comment by multimeric** [comment] 2022-09-21 00:08
Yes, I just checked and the CRAN version definitely has the patch that I made for this bug. Can you share a file that can reproduce this error so I can investigate?

**Comment by wish1832** [comment] 2022-09-21 16:49
Hello,

Below is the file that causes the error. This one doesn't load on either the version installed from CRAN, the version installed from github, or the version installed using `remotes::install_github("multimeric/TidyMultiqc@fix-list-general", force=TRUE)`. 

[salmon_error.json.txt](https://github.com/multimeric/TidyMultiqc/files/9618752/salmon_error.json.txt)

The error message was encountered when running:
```
load_multiqc(
  "salmon_error.json", 
  sections = "raw"
  )
```
> Error: Can't recycle `raw.salmon.salmon_version` (size 2) to match `raw.salmon.length_classes` (size 5).

Thank you!

**Comment by multimeric** [comment] 2022-09-23 12:25
Hi @wish1832, I've opened a PR I believe should fix this. Can you try `remotes::install_github("multimeric/TidyMultiqc@raw-salmon", force=TRUE)` and see if that resolves your issue?

**Closed as completed** 2022-09-25 01:17 UTC

**Comment by wish1832** [comment] 2022-09-26 15:39
Hi @multimeric, 

That fix worked, thank you!!

**Comment by multimeric** [comment] 2022-09-26 22:50
The fix is now on CRAN, also.
